### ISSUE TITLE
ทำเอกสาร (Stream Sound via Network)

### ISSUE THREAD

**Issue by Cluster-APX** [XPrize-Perception-Team/fibo.xprize.perception#12]
เนื้อหาจาก https://github.com/XPrize-Perception-Team/fibo.xprize.perception/issues/7

**Comment by Cluster-APX** [comment]
1. https://github.com/XPrize-Perception-Team/fibo.xprize.perception/tree/master/Sound.Avatar/Stereo%20Sound%20via%20Server
2. https://github.com/XPrize-Perception-Team/fibo.xprize.perception/tree/master/Sound.Operator/StereoSound%20via%20Server

**Comment by yachinji** [comment]
ตรวจแล้ว
