### ISSUE TITLE
Avatar Stereo Input (Microphone)

### ISSUE THREAD

**Issue by Cluster-APX** [XPrize-Perception-Team/fibo.xprize.perception#29]
ออกแบบและพัฒนารูปแบบการส่งสัญญาณเสียง Analog เข้าสู่ PC (3.5 mic) และโครงสร้างรูปร่างคล้ายหูมนุษย์สำหรับยึด mic เสมือนมีหู 2 ข้าง

**Comment by yachinji** [comment]
ตรวจแล้ว
