### ISSUE TITLE
ส่งค่า Rotation ของ Operator ไปยัง Avatar

### ISSUE THREAD

**Issue by Cluster-APX** [XPrize-Perception-Team/fibo.xprize.perception#6]
อ่านข้อมูลจาก HMD แล้วแปลงข้อมูล Roll, Pitch, Yaw (-90 ถึง +90) จาก Operator (Unity) ส่งไปยัง Avatar (Dynamixel) ผ่าน mqtt เพื่อขยับหัว Avatar

**Comment by aminballoon** [comment]
อันนี้ผมจองง

**Comment by aminballoon** [comment]
อันนี้ ผมทำครับ

**Comment by Cluster-APX** [comment]
อาจจะเปลี่ยนเป็น Quaternion

**Comment by yachinji** [comment]
ตรวจแล้ว
