### ISSUE TITLE
ซื้อ ZED mini

### ISSUE THREAD

**Issue by Cluster-APX** [XPrize-Perception-Team/fibo.xprize.perception#61]
ซื้อ ZED mini จำนวน 1 ตัว สำหรับการส่งภาพ RGB แบบ Stereoscopic (Direct Mode) https://github.com/XPrize-Perception-Team/fibo.xprize.perception/issues/5 และ Virtual Reality Mode โดยเฉพาะระหว่างการสนทนาระหว่าง Operator -> Avatar กับ Recipient

Product : https://www.stereolabs.com/zed-mini/
Specification : https://cdn.stereolabs.com/assets/datasheets/zed-mini-camera-datasheet.pdf

**SDK System Requirements**
> Dual-core 2.3GHz or faster processor
> 4 GB RAM or more
> Nvidia GPU with compute capability > 3.0

**Comment by yachinji** [comment]
กำลังขอใบเสนอราคา

**Comment by Cluster-APX** [comment]
ซื้อแล้ว 1 ตัว  ส่งให้ XPRIZE แล้ว (วันนี้)
