### ISSUE TITLE
ซื้อ microphone 2 ตัว

### ISSUE THREAD

**Issue by RyuuseiX** [XPrize-Perception-Team/fibo.xprize.perception#68]
microphone 2 ตัว ไว้ตัด noise สำหรับฝั่ง operator *ถ้าไมค์ที่หูหุ่นปัจจุบันไม่ใช้แล้วก็ใช้อันนั้นก็ได้ครับ*

**Comment by Cluster-APX** [comment]
ซื้อแล้ว ที่ใช้ในงาน 25 ปี FIBO #39
